### ISSUE TITLE
make transport mechanism pluggable

### ISSUE THREAD

**Issue by robertkowalski** [KlausTrainer/couch_email_auth#28]
Let's provide support for email by default, but if I want to send SMS I should be able to plug that functionality in. This might conflict with some parts of https://github.com/KlausTrainer/couch_email_auth/issues/23

**Comment by KlausTrainer** [comment]
This is out of scope for now. For now, I'd prefer to have this done within a fork, in order to keep couch_email_auth focused. It would also imply a renaming.
